export type PerfumeProduct = {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: string;
  oldPrice: string;
  badge: string;
  image: string;
  availability: "Disponible" | "Stock limité";
  notes: string;
  tone: {
    primary: string;
    secondary: string;
  };
};

export const perfumes: PerfumeProduct[] = [
  {
    id: "oud-royal",
    name: "Oud Royal",
    brand: "Achraf Signature",
    category: "Homme",
    price: "299 DH",
    oldPrice: "379 DH",
    badge: "Best Seller",
    image: "/images/Oud%20Wood.jpeg",
    availability: "Disponible",
    notes: "Oud, ambre, bois précieux",
    tone: { primary: "#588b76", secondary: "#f6f6df" },
  },
  {
    id: "rose-privee",
    name: "Rose Privée",
    brand: "Maison Florale",
    category: "Femme",
    price: "319 DH",
    oldPrice: "399 DH",
    badge: "Nouveau",
    image: "/images/Baccarat%20Rouge.jpeg",
    availability: "Stock limité",
    notes: "Rose, musc blanc, vanille",
    tone: { primary: "#b9868f", secondary: "#fff5f1" },
  },
  {
    id: "musc-blanc",
    name: "Musc Blanc",
    brand: "Pure Collection",
    category: "Mixte",
    price: "249 DH",
    oldPrice: "299 DH",
    badge: "Iconique",
    image: "/images/images%20(1).jpeg",
    availability: "Disponible",
    notes: "Musc, coton, iris",
    tone: { primary: "#d9c7a3", secondary: "#fffef7" },
  },
  {
    id: "ambre-nuit",
    name: "Ambre Nuit",
    brand: "Nocturne",
    category: "Homme",
    price: "349 DH",
    oldPrice: "429 DH",
    badge: "Intense",
    image: "/images/Oriental.jpeg",
    availability: "Disponible",
    notes: "Ambre, épices, cèdre",
    tone: { primary: "#9b6b45", secondary: "#f6f6df" },
  },
  {
    id: "neroli-satin",
    name: "Néroli Satin",
    brand: "Riviera",
    category: "Femme",
    price: "289 DH",
    oldPrice: "349 DH",
    badge: "Frais",
    image: "/images/perfums1.jpeg",
    availability: "Disponible",
    notes: "Néroli, fleur d&apos;oranger, musc",
    tone: { primary: "#d7a85e", secondary: "#fff8e6" },
  },
  {
    id: "cuir-vert",
    name: "Cuir Vert",
    brand: "Atelier Privé",
    category: "Mixte",
    price: "369 DH",
    oldPrice: "459 DH",
    badge: "Premium",
    image: "/images/Oud%20Wood.jpeg",
    availability: "Stock limité",
    notes: "Cuir, vétiver, sauge",
    tone: { primary: "#426c5d", secondary: "#edf4ec" },
  },
  {
    id: "vanille-doree",
    name: "Vanille Dorée",
    brand: "Gourmand Luxe",
    category: "Femme",
    price: "279 DH",
    oldPrice: "339 DH",
    badge: "Doux",
    image: "/images/vanilla-sex-tom-ford.png",
    availability: "Disponible",
    notes: "Vanille, fève tonka, caramel",
    tone: { primary: "#c99a52", secondary: "#fff1d6" },
  },
  {
    id: "bois-imperial",
    name: "Bois Impérial",
    brand: "Royal Woods",
    category: "Homme",
    price: "389 DH",
    oldPrice: "479 DH",
    badge: "Luxe",
    image: "/images/Oud%20Wood.jpeg",
    availability: "Disponible",
    notes: "Bois sec, patchouli, encens",
    tone: { primary: "#2f463f", secondary: "#f6f6df" },
  },
  {
    id: "jasmin-ivoire",
    name: "Jasmin Ivoire",
    brand: "Floral Couture",
    category: "Femme",
    price: "309 DH",
    oldPrice: "389 DH",
    badge: "Élégant",
    image: "/images/femme.jpeg",
    availability: "Disponible",
    notes: "Jasmin, poire, muscs",
    tone: { primary: "#9d8f62", secondary: "#fffef7" },
  },
  {
    id: "citrus-marine",
    name: "Citrus Marine",
    brand: "Fresh Line",
    category: "Mixte",
    price: "239 DH",
    oldPrice: "299 DH",
    badge: "Été",
    image: "/images/Bleu%20de%20Chanel.jpeg",
    availability: "Disponible",
    notes: "Bergamote, sel marin, bois clair",
    tone: { primary: "#4f91a3", secondary: "#eaf7f4" },
  },
  {
    id: "tabac-velours",
    name: "Tabac Velours",
    brand: "Evening Blend",
    category: "Homme",
    price: "359 DH",
    oldPrice: "449 DH",
    badge: "Charme",
    image: "/images/Dior%20Sauvage.jpeg",
    availability: "Stock limité",
    notes: "Tabac blond, miel, fève tonka",
    tone: { primary: "#815838", secondary: "#f4ead8" },
  },
  {
    id: "poudre-rose",
    name: "Poudre Rose",
    brand: "Soft Maison",
    category: "Femme",
    price: "269 DH",
    oldPrice: "329 DH",
    badge: "Délicat",
    image: "/images/SCANDAL_INTENSE_JEAN_PAUL_GAULTIER_foryou.ma.webp",
    availability: "Disponible",
    notes: "Rose poudrée, violette, musc",
    tone: { primary: "#c18fa0", secondary: "#fff2f4" },
  },
];
